import 'package:dynamic_color/dynamic_color.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:logger/logger.dart';
import 'core/di/providers.dart';
import 'core/router/app_router.dart';
import 'services/database/daos/settings_dao.dart';
import 'core/sentry_config.dart';
import 'core/theme/soul_theme.dart';
import 'generated/terminal_bridge.g.dart';
import 'objectbox.g.dart'; // Generated by ObjectBox
import 'services/awareness/soul_awareness_service.dart';
import 'services/auth/api_key_service.dart';
import 'services/vessels/openclaw/openclaw_client.dart';
import 'services/vessels/openclaw/openclaw_config.dart';

final _logger = Logger();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await _initAndRun();
  } catch (error, stackTrace) {
    _logger.e('Fatal init error: $error\n$stackTrace');
    // Show error on screen so it's visible for debugging
    runApp(
      MaterialApp(
        home: Scaffold(
          backgroundColor: const Color(0xFF1A0000),
          body: SafeArea(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Text(
                'SOUL Init Error:\n\n$error\n\n$stackTrace',
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 12,
                  fontFamily: 'monospace',
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

Future<void> _initAndRun() async {
  // Initialize ObjectBox store
  final store = await openStore();

  final container = ProviderContainer(
    overrides: [
      objectBoxStoreProvider.overrideWithValue(store),
    ],
  );

  // Load Anthropic API key from secure storage and inject into provider.
  final apiKeyService = ApiKeyService();
  String savedKey = '';
  try {
    savedKey = await apiKeyService.getAnthropicKey() ?? '';
    if (savedKey.isNotEmpty) {
      container.read(apiKeyNotifierProvider.notifier).setKey(savedKey);
    }
  } catch (error) {
    _logger.e('Failed to load API key: $error');
  }

  // Initialize OpenClaw client from saved credentials
  try {
    final hasOpenClaw = await apiKeyService.hasOpenClawCredentials();
    if (hasOpenClaw) {
      final host = await apiKeyService.getOpenClawHost();
      final token = await apiKeyService.getOpenClawToken();
      final useTls = await apiKeyService.getOpenClawUseTls();
      final config = OpenClawConfig(
        host: host!,
        port: useTls ? 443 : 18789,
        token: token!,
        useTls: useTls,
      );
      final client = OpenClawClient(config: config);
      await client.connect();
      container.read(vesselManagerProvider).setOpenClawClient(client);
      _logger.i('OpenClaw client initialized: ${config.baseUrl}');
    }
  } catch (error) {
    _logger.e('Failed to initialize OpenClaw client: $error');
  }

  // Initialize local notification service
  try {
    final notificationService = container.read(localNotificationServiceProvider);
    await notificationService.initialize();
    _logger.i('Local notification service initialized');
  } catch (error) {
    _logger.e('Failed to initialize notification service: $error');
  }

  // Initialize and start foreground service
  try {
    final serviceManager = container.read(foregroundServiceManagerProvider);
    serviceManager.initialize();
    await serviceManager.startService();
    _logger.i('Foreground service started');
  } catch (error) {
    _logger.e('Failed to start foreground service: $error');
  }

  // Check if setup wizard has been completed
  String initialLocation = '/setup-wizard';
  try {
    final settingsDao = container.read(settingsDaoProvider);
    final isSetupComplete = await settingsDao.getBool(SettingsKeys.setupCompleted) ?? false;

    if (isSetupComplete) {
      try {
        final projectDao = container.read(projectDaoProvider);
        final activeProject = await projectDao.getActiveProject();
        final hasProjects = activeProject != null;
        initialLocation = (hasProjects && savedKey.isNotEmpty) ? '/' : '/chat/new';
      } catch (error) {
        _logger.e('Failed to check projects: $error');
        initialLocation = '/chat/new';
      }
    }
  } catch (error) {
    _logger.e('Failed to check setup status: $error');
  }

  await SentryConfig.init(
    appRunner: () async {
      runApp(
        UncontrolledProviderScope(
          container: container,
          child: SoulApp(initialLocation: initialLocation),
        ),
      );
    },
  );
}

class SoulApp extends StatefulWidget {
  final String initialLocation;

  const SoulApp({super.key, required this.initialLocation});

  @override
  State<SoulApp> createState() => _SoulAppState();
}

class _SoulAppState extends State<SoulApp> implements SoulBridgeApi {
  late final _router = createAppRouter(initialLocation: widget.initialLocation);

  @override
  void initState() {
    super.initState();
    SoulBridgeApi.setUp(this);
  }

  @override
  void dispose() {
    SoulBridgeApi.setUp(null);
    super.dispose();
  }

  // SoulBridgeApi implementation — called from host (Java) side
  @override
  void onTerminalOutput(String output) {
    _logger.d('Terminal output received: ${output.length} chars');
    try {
      final container = ProviderScope.containerOf(context);
      container.read(soulAwarenessProvider.notifier).onTerminalOutput(output);
    } catch (e) {
      _logger.e('Failed to route terminal output: $e');
    }
  }

  @override
  void onSessionChanged(SessionInfo info) {
    _logger.d('Session changed: ${info.name}');
  }

  @override
  void onSessionListChanged(List<SessionInfo> sessions) {
    _logger.d('Session list changed: ${sessions.length} sessions');
  }

  @override
  void onCommandCompleted(int sessionId) {
    _logger.d('Command completed in session $sessionId');
    try {
      final container = ProviderScope.containerOf(context);
      container.read(soulAwarenessProvider.notifier).onCommandCompleted(sessionId);
    } catch (e) {
      _logger.e('Failed to route onCommandCompleted: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return DynamicColorBuilder(
      builder: (ColorScheme? lightDynamic, ColorScheme? darkDynamic) {
        return MaterialApp.router(
          title: 'SOUL',
          theme: SoulTheme.light(lightDynamic),
          darkTheme: SoulTheme.dark(darkDynamic),
          themeMode: ThemeMode.system,
          routerConfig: _router,
          debugShowCheckedModeBanner: false,
        );
      },
    );
  }
}
