// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/message_embedding.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 601960131177440489),
    name: 'MessageEmbedding',
    lastPropertyId: const obx_int.IdUid(5, 721659450346631550),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6143973308257001859),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 865358826052745731),
        name: 'sourceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6266248424585230495),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5998511270578894328),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4540274809632313820),
        name: 'sourceText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 721659450346631550),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 485811392390534030),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 601960131177440489),
    lastIndexId: const obx_int.IdUid(2, 485811392390534030),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MessageEmbedding: obx_int.EntityDefinition<MessageEmbedding>(
      model: _entities[0],
      toOneRelations: (MessageEmbedding object) => [],
      toManyRelations: (MessageEmbedding object) => {},
      getId: (MessageEmbedding object) => object.obxId,
      setId: (MessageEmbedding object, int id) {
        object.obxId = id;
      },
      objectToFB: (MessageEmbedding object, fb.Builder fbb) {
        final sourceIdOffset = fbb.writeString(object.sourceId);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final sourceTextOffset = object.sourceText == null
            ? null
            : fbb.writeString(object.sourceText!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(6);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, sourceIdOffset);
        fbb.addOffset(2, sourceTypeOffset);
        fbb.addOffset(3, sourceTextOffset);
        fbb.addOffset(4, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sourceTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = MessageEmbedding(
          sourceId: sourceIdParam,
          sourceType: sourceTypeParam,
          sourceText: sourceTextParam,
          embedding: embeddingParam,
        )..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MessageEmbedding] entity fields to define ObjectBox queries.
class MessageEmbedding_ {
  /// See [MessageEmbedding.obxId].
  static final obxId = obx.QueryIntegerProperty<MessageEmbedding>(
    _entities[0].properties[0],
  );

  /// See [MessageEmbedding.sourceId].
  static final sourceId = obx.QueryStringProperty<MessageEmbedding>(
    _entities[0].properties[1],
  );

  /// See [MessageEmbedding.sourceType].
  static final sourceType = obx.QueryStringProperty<MessageEmbedding>(
    _entities[0].properties[2],
  );

  /// See [MessageEmbedding.sourceText].
  static final sourceText = obx.QueryStringProperty<MessageEmbedding>(
    _entities[0].properties[3],
  );

  /// See [MessageEmbedding.embedding].
  static final embedding = obx.QueryHnswProperty<MessageEmbedding>(
    _entities[0].properties[4],
  );
}
