package com.termux.bridge;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.termux.app.ProfilePackInstaller;
import com.termux.shared.logger.Logger;

/**
 * Host-side implementation of ProfilePackBridgeApi (generated by Pigeon).
 * Delegates to ProfilePackInstaller for zip extraction and verification.
 */
public class ProfilePackBridgeImpl implements ProfilePackBridgeApi.HostApi {

    private static final String LOG_TAG = "ProfilePackBridgeImpl";

    @Override
    @Nullable
    public String extractProfilePack(@NonNull String zipFilePath, @NonNull String profileId, @NonNull String version) {
        Logger.logInfo(LOG_TAG, "extractProfilePack: " + profileId + " v" + version + " from " + zipFilePath);
        return ProfilePackInstaller.extractProfilePack(zipFilePath, profileId, version);
    }

    @Override
    @NonNull
    public Boolean verifySha256(@NonNull String filePath, @NonNull String expectedHash) {
        return ProfilePackInstaller.verifySha256(filePath, expectedHash);
    }

    @Override
    @Nullable
    public String getInstalledProfileVersion(@NonNull String profileId) {
        return ProfilePackInstaller.getInstalledProfileVersion(profileId);
    }

    @Override
    @Nullable
    public String getInterruptedInstallation() {
        return ProfilePackInstaller.getInterruptedInstallation();
    }
}
