// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers
package com.termux.bridge;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated class from Pigeon.
 *
 * <p>See also: https://pub.dev/packages/pigeon
 */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class SystemBridgeApi {
  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  /** Device hardware and OS information. */
  public static final class DeviceInfo {
    private @NonNull String manufacturer;

    public @NonNull String getManufacturer() {
      return manufacturer;
    }

    public void setManufacturer(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"manufacturer\" is null.");
      }
      this.manufacturer = setterArg;
    }

    private @NonNull String model;

    public @NonNull String getModel() {
      return model;
    }

    public void setModel(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"model\" is null.");
      }
      this.model = setterArg;
    }

    private @NonNull String androidVersion;

    public @NonNull String getAndroidVersion() {
      return androidVersion;
    }

    public void setAndroidVersion(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"androidVersion\" is null.");
      }
      this.androidVersion = setterArg;
    }

    private @NonNull Long sdkInt;

    public @NonNull Long getSdkInt() {
      return sdkInt;
    }

    public void setSdkInt(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"sdkInt\" is null.");
      }
      this.sdkInt = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DeviceInfo() {}

    public static final class Builder {
      private @Nullable String manufacturer;

      public @NonNull Builder setManufacturer(@NonNull String setterArg) {
        this.manufacturer = setterArg;
        return this;
      }

      private @Nullable String model;

      public @NonNull Builder setModel(@NonNull String setterArg) {
        this.model = setterArg;
        return this;
      }

      private @Nullable String androidVersion;

      public @NonNull Builder setAndroidVersion(@NonNull String setterArg) {
        this.androidVersion = setterArg;
        return this;
      }

      private @Nullable Long sdkInt;

      public @NonNull Builder setSdkInt(@NonNull Long setterArg) {
        this.sdkInt = setterArg;
        return this;
      }

      public @NonNull DeviceInfo build() {
        DeviceInfo pigeonReturn = new DeviceInfo();
        pigeonReturn.setManufacturer(manufacturer);
        pigeonReturn.setModel(model);
        pigeonReturn.setAndroidVersion(androidVersion);
        pigeonReturn.setSdkInt(sdkInt);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(manufacturer);
      toListResult.add(model);
      toListResult.add(androidVersion);
      toListResult.add(sdkInt);
      return toListResult;
    }

    static @NonNull DeviceInfo fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DeviceInfo pigeonResult = new DeviceInfo();
      Object manufacturer = pigeonVar_list.get(0);
      pigeonResult.setManufacturer((String) manufacturer);
      Object model = pigeonVar_list.get(1);
      pigeonResult.setModel((String) model);
      Object androidVersion = pigeonVar_list.get(2);
      pigeonResult.setAndroidVersion((String) androidVersion);
      Object sdkInt = pigeonVar_list.get(3);
      pigeonResult.setSdkInt((sdkInt == null) ? null : ((sdkInt instanceof Integer) ? (long) (Integer) sdkInt : (Long) sdkInt));
      return pigeonResult;
    }
  }

  /** App package and build information. */
  public static final class PackageInfo {
    private @NonNull String packageName;

    public @NonNull String getPackageName() {
      return packageName;
    }

    public void setPackageName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packageName\" is null.");
      }
      this.packageName = setterArg;
    }

    private @NonNull String versionName;

    public @NonNull String getVersionName() {
      return versionName;
    }

    public void setVersionName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"versionName\" is null.");
      }
      this.versionName = setterArg;
    }

    private @NonNull Long versionCode;

    public @NonNull Long getVersionCode() {
      return versionCode;
    }

    public void setVersionCode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"versionCode\" is null.");
      }
      this.versionCode = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PackageInfo() {}

    public static final class Builder {
      private @Nullable String packageName;

      public @NonNull Builder setPackageName(@NonNull String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable String versionName;

      public @NonNull Builder setVersionName(@NonNull String setterArg) {
        this.versionName = setterArg;
        return this;
      }

      private @Nullable Long versionCode;

      public @NonNull Builder setVersionCode(@NonNull Long setterArg) {
        this.versionCode = setterArg;
        return this;
      }

      public @NonNull PackageInfo build() {
        PackageInfo pigeonReturn = new PackageInfo();
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setVersionName(versionName);
        pigeonReturn.setVersionCode(versionCode);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(packageName);
      toListResult.add(versionName);
      toListResult.add(versionCode);
      return toListResult;
    }

    static @NonNull PackageInfo fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PackageInfo pigeonResult = new PackageInfo();
      Object packageName = pigeonVar_list.get(0);
      pigeonResult.setPackageName((String) packageName);
      Object versionName = pigeonVar_list.get(1);
      pigeonResult.setVersionName((String) versionName);
      Object versionCode = pigeonVar_list.get(2);
      pigeonResult.setVersionCode((versionCode == null) ? null : ((versionCode instanceof Integer) ? (long) (Integer) versionCode : (Long) versionCode));
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return DeviceInfo.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return PackageInfo.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof DeviceInfo) {
        stream.write(129);
        writeValue(stream, ((DeviceInfo) value).toList());
      } else if (value instanceof PackageInfo) {
        stream.write(130);
        writeValue(stream, ((PackageInfo) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /**
   * Host API: Flutter calls these methods, Java implements them.
   * Provides device and app metadata.
   *
   * <p>Generated interface from Pigeon that represents a handler of messages from Java.
   */
  public interface HostApi {
    /** Get device hardware and OS information. */
    @NonNull
    DeviceInfo getDeviceInfo();

    /** Get app package and version information. */
    @NonNull
    PackageInfo getPackageInfo();

    /** The codec used by HostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }

    /**
     * Sets up an instance of `HostApi` to handle messages through the `binaryMessenger`.
     */
    static void setUp(
        @NonNull BinaryMessenger binaryMessenger, @Nullable HostApi api) {
      setUp(binaryMessenger, "", api);
    }

    static void setUp(
        @NonNull BinaryMessenger binaryMessenger,
        @NonNull String messageChannelSuffix,
        @Nullable HostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.SystemBridgeApi.getDeviceInfo" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  DeviceInfo output = api.getDeviceInfo();
                  wrapped.add(0, output);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.SystemBridgeApi.getPackageInfo" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  PackageInfo output = api.getPackageInfo();
                  wrapped.add(0, output);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
          "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  /**
   * Reply interface for asynchronous callbacks.
   */
  public interface Reply<T> {
    void reply(T reply);
  }
}
