package com.termux.bridge;

import android.content.Context;
import android.content.pm.PackageManager;
import android.os.Build;

import androidx.annotation.NonNull;

import com.termux.shared.logger.Logger;

/**
 * Host-side implementation of SystemBridgeApi (generated by Pigeon).
 * Provides device and app metadata to Flutter.
 */
public class SystemBridgeImpl implements SystemBridgeApi.SystemBridgeApi {

    private static final String LOG_TAG = "SystemBridgeImpl";
    private final Context mContext;

    public SystemBridgeImpl(@NonNull Context context) {
        mContext = context.getApplicationContext();
    }

    @NonNull
    @Override
    public SystemBridgeApi.DeviceInfo getDeviceInfo() {
        return new SystemBridgeApi.DeviceInfo.Builder()
            .setManufacturer(Build.MANUFACTURER)
            .setModel(Build.MODEL)
            .setAndroidVersion(Build.VERSION.RELEASE)
            .setSdkInt((long) Build.VERSION.SDK_INT)
            .build();
    }

    @NonNull
    @Override
    public SystemBridgeApi.PackageInfo getPackageInfo() {
        String packageName = mContext.getPackageName();
        String versionName = "unknown";
        long versionCode = 0;

        try {
            android.content.pm.PackageInfo info =
                mContext.getPackageManager().getPackageInfo(packageName, 0);
            versionName = info.versionName;
            versionCode = info.getLongVersionCode();
        } catch (PackageManager.NameNotFoundException e) {
            Logger.logError(LOG_TAG, "Failed to get package info: " + e.getMessage());
        }

        return new SystemBridgeApi.PackageInfo.Builder()
            .setPackageName(packageName)
            .setVersionName(versionName)
            .setVersionCode(versionCode)
            .build();
    }
}
