package com.termux.bridge;

import androidx.annotation.NonNull;

import com.termux.app.TermuxService;
import com.termux.shared.shell.TermuxSession;
import com.termux.shared.logger.Logger;
import com.termux.terminal.TerminalSession;

import java.util.ArrayList;
import java.util.List;

/**
 * Host-side implementation of TerminalBridgeApi (generated by Pigeon).
 * Bridges Flutter commands to the Termux terminal service.
 */
public class TerminalBridgeImpl implements TerminalBridgeApi.TerminalBridgeApi {

    private static final String LOG_TAG = "TerminalBridgeImpl";
    private final TermuxService mTermuxService;

    public TerminalBridgeImpl(@NonNull TermuxService termuxService) {
        mTermuxService = termuxService;
    }

    @Override
    public void executeCommand(@NonNull String command) {
        TerminalSession currentSession = getCurrentTerminalSession();
        if (currentSession != null) {
            currentSession.write(command + "\n");
            Logger.logDebug(LOG_TAG, "Executed command: " + command);
        } else {
            Logger.logWarn(LOG_TAG, "No active terminal session for command execution");
        }
    }

    @NonNull
    @Override
    public String getTerminalOutput(@NonNull Long lines) {
        TerminalSession currentSession = getCurrentTerminalSession();
        if (currentSession == null || currentSession.getEmulator() == null) {
            return "";
        }

        String fullTranscript = currentSession.getEmulator().getScreen().getTranscriptText();
        if (fullTranscript.isEmpty()) return "";

        // Return last N lines
        String[] allLines = fullTranscript.split("\n");
        int startIndex = Math.max(0, allLines.length - lines.intValue());
        StringBuilder result = new StringBuilder();
        for (int i = startIndex; i < allLines.length; i++) {
            if (i > startIndex) result.append("\n");
            result.append(allLines[i]);
        }
        return result.toString();
    }

    @NonNull
    @Override
    public Long createSession() {
        TermuxSession newSession = mTermuxService.createTermuxSession(
            null, null, null, null, false, null
        );
        if (newSession != null) {
            int index = mTermuxService.getIndexOfSession(newSession.getTerminalSession());
            Logger.logDebug(LOG_TAG, "Created new session at index: " + index);
            return (long) index;
        }
        return -1L;
    }

    @NonNull
    @Override
    public List<TerminalBridgeApi.SessionInfo> listSessions() {
        List<TerminalBridgeApi.SessionInfo> result = new ArrayList<>();
        List<TermuxSession> sessions = mTermuxService.getTermuxSessions();
        for (int i = 0; i < sessions.size(); i++) {
            TermuxSession termuxSession = sessions.get(i);
            TerminalSession terminalSession = termuxSession.getTerminalSession();
            String sessionName = terminalSession.mSessionName != null
                ? terminalSession.mSessionName
                : "Session " + (i + 1);
            TerminalBridgeApi.SessionInfo info = new TerminalBridgeApi.SessionInfo.Builder()
                .setId((long) i)
                .setName(sessionName)
                .setIsRunning(terminalSession.isRunning())
                .build();
            result.add(info);
        }
        return result;
    }

    private TerminalSession getCurrentTerminalSession() {
        if (mTermuxService.isTermuxSessionsEmpty()) return null;
        TermuxSession lastSession = mTermuxService.getLastTermuxSession();
        return lastSession != null ? lastSession.getTerminalSession() : null;
    }
}
