// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers
package com.termux.bridge;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated class from Pigeon.
 *
 * <p>See also: https://pub.dev/packages/pigeon
 */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class TerminalBridgeApi {
  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  /** Data class for terminal session info. */
  public static final class SessionInfo {
    private @NonNull Long id;

    public @NonNull Long getId() {
      return id;
    }

    public void setId(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    private @NonNull String name;

    public @NonNull String getName() {
      return name;
    }

    public void setName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"name\" is null.");
      }
      this.name = setterArg;
    }

    private @NonNull Boolean isRunning;

    public @NonNull Boolean getIsRunning() {
      return isRunning;
    }

    public void setIsRunning(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isRunning\" is null.");
      }
      this.isRunning = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    SessionInfo() {}

    /** Constructs a new instance with non-optional fields. */
    public static final class Builder {
      private @Nullable Long id;

      public @NonNull Builder setId(@NonNull Long setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String name;

      public @NonNull Builder setName(@NonNull String setterArg) {
        this.name = setterArg;
        return this;
      }

      private @Nullable Boolean isRunning;

      public @NonNull Builder setIsRunning(@NonNull Boolean setterArg) {
        this.isRunning = setterArg;
        return this;
      }

      public @NonNull SessionInfo build() {
        SessionInfo pigeonReturn = new SessionInfo();
        pigeonReturn.setId(id);
        pigeonReturn.setName(name);
        pigeonReturn.setIsRunning(isRunning);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(id);
      toListResult.add(name);
      toListResult.add(isRunning);
      return toListResult;
    }

    static @NonNull SessionInfo fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      SessionInfo pigeonResult = new SessionInfo();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((id == null) ? null : ((id instanceof Integer) ? (long) (Integer) id : (Long) id));
      Object name = pigeonVar_list.get(1);
      pigeonResult.setName((String) name);
      Object isRunning = pigeonVar_list.get(2);
      pigeonResult.setIsRunning((Boolean) isRunning);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return SessionInfo.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof SessionInfo) {
        stream.write(129);
        writeValue(stream, ((SessionInfo) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /**
   * Host API: Flutter calls these methods, Java implements them.
   * Handles terminal command execution and session management.
   *
   * <p>Generated interface from Pigeon that represents a handler of messages from Flutter.
   */
  public interface HostApi {
    /** Execute a command in the active terminal session. */
    void executeCommand(@NonNull String command);

    /** Get the last N lines of terminal output. */
    @NonNull
    String getTerminalOutput(@NonNull Long lines);

    /** Create a new terminal session. Returns the session index. */
    @NonNull
    Long createSession();

    /** List all active terminal sessions. */
    @NonNull
    List<SessionInfo> listSessions();

    /** Close a terminal session by index. Switches to adjacent session. */
    void closeSession(@NonNull Long id);

    /** Switch to a terminal session by index. */
    void switchSession(@NonNull Long id);

    /** Rename a terminal session by index. */
    void renameSession(@NonNull Long id, @NonNull String name);

    /** Run a structured command in a specific session (executable + args). Security whitelist checked. */
    void runCommand(@NonNull Long sessionId, @NonNull String executable, @NonNull List<String> args);

    /** Send raw text input to a specific terminal session. */
    void sendInput(@NonNull Long sessionId, @NonNull String text);

    /** Open the terminal bottom sheet to half-expanded state. */
    void openTerminalSheet();

    /** Create a dedicated SOUL awareness session. Returns session index. */
    @NonNull
    Long createAwarenessSession();

    /** The codec used by HostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }

    /**
     * Sets up an instance of `HostApi` to handle messages through the `binaryMessenger`.
     */
    static void setUp(
        @NonNull BinaryMessenger binaryMessenger, @Nullable HostApi api) {
      setUp(binaryMessenger, "", api);
    }

    static void setUp(
        @NonNull BinaryMessenger binaryMessenger,
        @NonNull String messageChannelSuffix,
        @Nullable HostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.executeCommand" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String arg_command = (String) args.get(0);
                try {
                  api.executeCommand(arg_command);
                  wrapped.add(0, null);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.getTerminalOutput" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number arg_linesArg = (Number) args.get(0);
                long arg_lines = (arg_linesArg == null) ? 0 : arg_linesArg.longValue();
                try {
                  String output = api.getTerminalOutput(arg_lines);
                  wrapped.add(0, output);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.createSession" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  Long output = api.createSession();
                  wrapped.add(0, output);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.listSessions" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  List<SessionInfo> output = api.listSessions();
                  wrapped.add(0, output);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.closeSession" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number arg_idArg = (Number) args.get(0);
                long arg_id = (arg_idArg == null) ? 0 : arg_idArg.longValue();
                try {
                  api.closeSession(arg_id);
                  wrapped.add(0, null);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.switchSession" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number arg_idArg = (Number) args.get(0);
                long arg_id = (arg_idArg == null) ? 0 : arg_idArg.longValue();
                try {
                  api.switchSession(arg_id);
                  wrapped.add(0, null);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.renameSession" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number arg_idArg = (Number) args.get(0);
                long arg_id = (arg_idArg == null) ? 0 : arg_idArg.longValue();
                String arg_name = (String) args.get(1);
                try {
                  api.renameSession(arg_id, arg_name);
                  wrapped.add(0, null);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.runCommand" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number arg_sessionIdArg = (Number) args.get(0);
                long arg_sessionId = (arg_sessionIdArg == null) ? 0 : arg_sessionIdArg.longValue();
                String arg_executable = (String) args.get(1);
                List<String> arg_args = (List<String>) args.get(2);
                try {
                  api.runCommand(arg_sessionId, arg_executable, arg_args);
                  wrapped.add(0, null);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.sendInput" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number arg_sessionIdArg = (Number) args.get(0);
                long arg_sessionId = (arg_sessionIdArg == null) ? 0 : arg_sessionIdArg.longValue();
                String arg_text = (String) args.get(1);
                try {
                  api.sendInput(arg_sessionId, arg_text);
                  wrapped.add(0, null);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.openTerminalSheet" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.openTerminalSheet();
                  wrapped.add(0, null);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_module.TerminalBridgeApi.createAwarenessSession" + messageChannelSuffix,
                getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  Long output = api.createAwarenessSession();
                  wrapped.add(0, output);
                } catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }

  /**
   * Flutter API: Java calls these methods, Dart implements them.
   * Streams terminal output and session events to Flutter.
   *
   * <p>Generated class from Pigeon that represents Flutter messages that can be called from Java.
   */
  public static class SoulBridgeApi {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public SoulBridgeApi(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }

    public SoulBridgeApi(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffixArg) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffixArg.isEmpty() ? "" : "." + messageChannelSuffixArg;
    }

    public @NonNull BinaryMessenger getBinaryMessenger() {
      return binaryMessenger;
    }

    /** The codec used by SoulBridgeApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }

    /** Called when terminal output changes (debounced, max 10/sec). */
    public void onTerminalOutput(
        @NonNull String outputArg, @NonNull Reply<Object> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger,
              "dev.flutter.pigeon.flutter_module.SoulBridgeApi.onTerminalOutput" + messageChannelSuffix,
              getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(outputArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                callback.reply(
                    new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                callback.reply(null);
              }
            } else {
              callback.reply(new FlutterError("channel-error", "Unable to establish connection on channel.", ""));
            }
          });
    }

    /** Called when the active session changes. */
    public void onSessionChanged(
        @NonNull SessionInfo infoArg, @NonNull Reply<Object> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger,
              "dev.flutter.pigeon.flutter_module.SoulBridgeApi.onSessionChanged" + messageChannelSuffix,
              getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(infoArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                callback.reply(
                    new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                callback.reply(null);
              }
            } else {
              callback.reply(new FlutterError("channel-error", "Unable to establish connection on channel.", ""));
            }
          });
    }

    /** Called when the session list changes (add/remove/rename). */
    public void onSessionListChanged(
        @NonNull List<SessionInfo> sessionsArg, @NonNull Reply<Object> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger,
              "dev.flutter.pigeon.flutter_module.SoulBridgeApi.onSessionListChanged" + messageChannelSuffix,
              getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(sessionsArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                callback.reply(
                    new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                callback.reply(null);
              }
            } else {
              callback.reply(new FlutterError("channel-error", "Unable to establish connection on channel.", ""));
            }
          });
    }

    /** Called when a command finishes (OSC 133 prompt marker detected). */
    public void onCommandCompleted(
        @NonNull Long sessionIdArg, @NonNull Reply<Object> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger,
              "dev.flutter.pigeon.flutter_module.SoulBridgeApi.onCommandCompleted" + messageChannelSuffix,
              getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(sessionIdArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                callback.reply(
                    new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                callback.reply(null);
              }
            } else {
              callback.reply(new FlutterError("channel-error", "Unable to establish connection on channel.", ""));
            }
          });
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
          "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  /**
   * Reply interface for asynchronous callbacks.
   */
  public interface Reply<T> {
    void reply(T reply);
  }
}
