package com.termux.bridge;

import android.os.Handler;
import android.os.Looper;

import androidx.annotation.NonNull;

import com.termux.app.TermuxActivity;
import com.termux.app.TermuxService;
import com.termux.shared.termux.shell.command.runner.terminal.TermuxSession;
import com.termux.shared.logger.Logger;
import com.termux.terminal.TerminalSession;

import java.util.ArrayList;
import java.util.List;

/**
 * Host-side implementation of TerminalBridgeApi (generated by Pigeon).
 * Bridges Flutter commands to the Termux terminal service.
 */
public class TerminalBridgeImpl implements TerminalBridgeApi.HostApi {

    private static final String LOG_TAG = "TerminalBridgeImpl";
    private final TermuxService mTermuxService;
    private TermuxActivity mActivity;

    public TerminalBridgeImpl(@NonNull TermuxService termuxService) {
        mTermuxService = termuxService;
    }

    public void setActivity(TermuxActivity activity) {
        mActivity = activity;
    }

    @Override
    public void executeCommand(@NonNull String command) {
        TerminalSession currentSession = getCurrentTerminalSession();
        if (currentSession != null) {
            currentSession.write(command + "\n");
            Logger.logDebug(LOG_TAG, "Executed command: " + command);
        } else {
            Logger.logWarn(LOG_TAG, "No active terminal session for command execution");
        }
    }

    @NonNull
    @Override
    public String getTerminalOutput(@NonNull Long lines) {
        TerminalSession currentSession = getCurrentTerminalSession();
        if (currentSession == null || currentSession.getEmulator() == null) {
            return "";
        }

        String fullTranscript = currentSession.getEmulator().getScreen().getTranscriptText();
        if (fullTranscript.isEmpty()) return "";

        // Return last N lines
        String[] allLines = fullTranscript.split("\n");
        int startIndex = Math.max(0, allLines.length - lines.intValue());
        StringBuilder result = new StringBuilder();
        for (int i = startIndex; i < allLines.length; i++) {
            if (i > startIndex) result.append("\n");
            result.append(allLines[i]);
        }
        return result.toString();
    }

    @NonNull
    @Override
    public Long createSession() {
        TermuxSession newSession = mTermuxService.createTermuxSession(
            null, null, null, null, false, null
        );
        if (newSession != null) {
            int index = mTermuxService.getIndexOfSession(newSession.getTerminalSession());
            Logger.logDebug(LOG_TAG, "Created new session at index: " + index);
            return (long) index;
        }
        return -1L;
    }

    @NonNull
    @Override
    public List<TerminalBridgeApi.SessionInfo> listSessions() {
        List<TerminalBridgeApi.SessionInfo> result = new ArrayList<>();
        List<TermuxSession> sessions = mTermuxService.getTermuxSessions();
        for (int i = 0; i < sessions.size(); i++) {
            TermuxSession termuxSession = sessions.get(i);
            TerminalSession terminalSession = termuxSession.getTerminalSession();
            String sessionName = terminalSession.mSessionName != null
                ? terminalSession.mSessionName
                : "Session " + (i + 1);
            TerminalBridgeApi.SessionInfo info = new TerminalBridgeApi.SessionInfo.Builder()
                .setId((long) i)
                .setName(sessionName)
                .setIsRunning(terminalSession.isRunning())
                .build();
            result.add(info);
        }
        return result;
    }

    @Override
    public void closeSession(@NonNull Long id) {
        int index = id.intValue();
        if (index < 0 || index >= mTermuxService.getTermuxSessionsSize()) {
            Logger.logWarn(LOG_TAG, "closeSession: invalid index " + index);
            return;
        }
        if (mTermuxService.getTermuxSessionsSize() <= 1) {
            Logger.logWarn(LOG_TAG, "closeSession: cannot close last session");
            return;
        }
        TermuxSession session = mTermuxService.getTermuxSession(index);
        if (session != null) {
            new Handler(Looper.getMainLooper()).post(() ->
                session.getTerminalSession().finishIfRunning()
            );
        }
    }

    @Override
    public void switchSession(@NonNull Long id) {
        int index = id.intValue();
        if (mActivity != null) {
            new Handler(Looper.getMainLooper()).post(() ->
                mActivity.getTermuxTerminalSessionClient().switchToSession(index)
            );
        }
    }

    @Override
    public void renameSession(@NonNull Long id, @NonNull String name) {
        int index = id.intValue();
        TermuxSession session = mTermuxService.getTermuxSession(index);
        if (session != null) {
            new Handler(Looper.getMainLooper()).post(() -> {
                session.getTerminalSession().mSessionName = name;
                if (mActivity != null) {
                    mActivity.termuxSessionListNotifyUpdated();
                }
            });
        }
    }

    private TerminalSession getCurrentTerminalSession() {
        if (mActivity != null && mActivity.getTerminalView() != null) {
            return mActivity.getTerminalView().getCurrentSession();
        }
        // Fallback to last session if activity not available
        if (mTermuxService.isTermuxSessionsEmpty()) return null;
        TermuxSession lastSession = mTermuxService.getLastTermuxSession();
        return lastSession != null ? lastSession.getTerminalSession() : null;
    }
}
